CREATE TABLE ESTOQUE (
	id_fornecedor BIGINT NOT NULL,
	id_produto BIGINT NOT NULL,
    PRIMARY KEY (id_fornecedor, id_produto)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ESTOQUE ADD CONSTRAINT estoque_produto_fk FOREIGN KEY(id_produto) REFERENCES PRODUTO (id);

ALTER TABLE ESTOQUE ADD CONSTRAINT estoque_fornecedor_fk FOREIGN KEY(id_fornecedor) REFERENCES FORNECEDOR (id);

INSERT INTO ESTOQUE VALUES (27, 1);
INSERT INTO ESTOQUE VALUES (28, 1);
INSERT INTO ESTOQUE VALUES (29, 1);
INSERT INTO ESTOQUE VALUES (46, 1);
INSERT INTO ESTOQUE VALUES (27, 2);
INSERT INTO ESTOQUE VALUES (28, 2);
INSERT INTO ESTOQUE VALUES (46, 2);
INSERT INTO ESTOQUE VALUES (29, 2);
INSERT INTO ESTOQUE VALUES (30, 2);
INSERT INTO ESTOQUE VALUES (31, 2);
INSERT INTO ESTOQUE VALUES (27, 3);
INSERT INTO ESTOQUE VALUES (28, 3);
INSERT INTO ESTOQUE VALUES (29, 3);
INSERT INTO ESTOQUE VALUES (27, 6);
INSERT INTO ESTOQUE VALUES (28, 6);
INSERT INTO ESTOQUE VALUES (29, 6);
INSERT INTO ESTOQUE VALUES (46, 6);
INSERT INTO ESTOQUE VALUES (27, 7);
INSERT INTO ESTOQUE VALUES (28, 7);
INSERT INTO ESTOQUE VALUES (46, 35);
